project:
  type: website
  resources:
    - "pdf/*.pdf"

website:
  title: "Home"  
  sidebar:
    search: false
    style: "floating"
    # collapse-level: 1
    contents:
        - section: "Lectures"
          contents:
            - text: Infinite Content
              file: w1-infinite-content.qmd
            - text: Our Algorithms, Ourselves
              file: w2a-algorithms.qmd
            - text: Algorithmic Anxiety
              file: w2b-algorithms.qmd
            - text: The Artist's Dilemma
              file: w3-influencers.qmd
        - section: "Resources"
          contents:
            - text: Theory as Narrative
              file: theory-narrative.qmd
  navbar:
    background: "#235440"
    right:
      - icon: github
        aria-label: github
        href: https://github.com/mroberts1/fsu-smt-su24
      # - icon: twitter
      #   aria-label: twitter
      #   href: https://twitter.com/mroberts_fsu
format:
  html:
    # toc: false
    # toc-depth: 2
    # toc-location: right
    # toc-title: '   '
    theme:
      light: [ember.scss, custom_callouts.scss]
      dark: [ember.scss, custom_callouts.scss, slate]
    css: custom.scss
    self-contained: false
    grid:
      body-width: 650px
    linestretch: 1.5
    fontsize: 1em
    smooth-scroll: true
    # linkcolor: "#235440"
    link-external-newwindow: true
  PrettyPDF-pdf: default
callout-appearance: default
bread-crumbs: false
fig-responsive: true
image-alt: " "
execute:
  freeze: auto
# reference-location: margin
# citation-location: margin
editor: visual
