---
title: The Artist\'s Dilemma
subtitle: Staged Authenticity and the Algorithmic Self
toc: false
---

::: column-margin
<br><br><br><br> <small>[Sophie Bishop](https://sophiebishop.co.uk/), "[Influencer Creep](https://reallifemag.com/influencer-creep/)"<br><br>[Sophie Bishop](https://sophiebishop.co.uk/), "[Influencer creep: How artists strategically navigate the platformisation of art worlds](https://journals.sagepub.com/doi/epub/10.1177/14614448231206090)"<br><br>See also:<br><br>[Sophie Bishop](https://sophiebishop.co.uk/), "[How to Research Online Influencers](https://sophiebishop.co.uk/wp-content/uploads/2023/12/how-to-research-online-influencers.pdf)"<br><br>[Sophie Bishop](https://sophiebishop.co.uk/), "[Influencer Management Tools: Algorithmic Cultures, Brand Safety, and Bias](https://journals.sagepub.com/doi/epub/10.1177/20563051211003066)"</small>
:::

Continuing our exploration of the "algorithmic self" from last week, Sophie Bishop's articles this week focus on the phenomenon of what she calls **influencer creep**: the encroachment of the logics and practices of professional influencers into all sectors of contemporary cultural production, driven by the imperative of **algorithmic visibility**---the necessity for one's content to be seen by the largest audience possible, along with the economic rewards that come with it.

"What is wrong with this?", you might ask. Bishop's critique---and we should be clear that it **is** a critique---is that in the domain of the art world, at least, the requirement to optimize not only one's work but one's very identity according to the requirements of the platform and its algorithm is transforming the nature of art itself as it has historically been practised, from prioritizing/de-prioritizing forms of artistic production that are platform-friendly (or not), as well as by forcing artists to stage and perform their work for their social media audiences. 

As Bishop explains, this situation is riven with contradictions: conflicting demands that often pull artists in opposing directions. Moreover, she argues, the new requirement that artists perform their aesthetic practices for an audience algorithmically privileges white content producers and often forces ethnic or racially other producers into a kind of "burden of representation" (though Bishop doesn't use this term) in which they and their work are reified by white audiences/consumers representative of a larger BIPOC/gender community, whether the artists themselves intend it or not.[For a satirical and very funny example of how ethnic artists can turn the primitivism of white audiences to their own advantage, see Nathan Fielder and Emma Stone's recent drama series, **The Curse**.]{.aside}

Bishop's arguments in both articles---the online journalism for the now-defunct online magazine [**Real Life**](https://reallifemag.com/) and the more detailed academic article  about her research---are conceptually straightforward, so I'm not going to reiterate the basic concepts here: influencer creep itself and its three main components (self-branding and affective labor; optimization; performed authenticity). The article re-intoduces some key concepts, notably **platformization** and Nick Srnicek's (pron. Ser-neck) concept of **platform capitalism**. 

From a methodological point of view, the article also provides an excellent introduction to the academic field of **digital ethnography**, or the application of ethnographic methods of research (notably the key method of **participant observation**) to social media cultures.

In terms of its theoretical framework, Bishop's discussion draws on a number of influential historical concepts from sociology, cultural studies, and media studies, notably Erving Goffman's **The Presentation of Self in Everyday Life** (1959) and Walter Benjamin's concept of **aura** elaborated in his celebrated essay "The Work of Art in the Age of Mechanical Reproduction" (1936). You may have encountered these texts in other courses, as they are widely read in undergraduate sociology and media theory courses. 

For reasons of space, I will limit myself here to highlighting a couple of concepts that Bishop frequently returns to and that I think are particularly useful to a theoretical understanding of the dynamics of influencer culture: the idea of **staging artistic practicies for the social media audience, and the related idea of a **backstage** that is a key component of authenticity; and the generalized state of anxiety produced in artists by the imperatives to publicly perform their role for the sake of algorithmic visibility.

**Staged Authenticity**\

Erving Goffman's influential notion of the self as something that is **performed** and **staged**in public life implies the idea of a **backstage** area---a private space "behind the scenes" which is the locus of the authentic self distinct from the public persona. Goffman's framework was elaborated further by Dean MacCannell in his landmark book about tourism, **The Tourist: A New Theory of the Leisure Class** (1976). For MacCannell, the entire tourist industry is organized around  a deeply paradoxical system of representation that he calls **staged authenticity**: touristic experiences also purport to take us "behind the scenes" of local cultures, in order to deliver what is always presented as an "authentic" experience of the cultural other but is simply staged and performed for the benefit of the tourist. This commodified "authenticity" actually serves as a kind of barrier or filter between the tourist and the actual lived experience of members of the culture in question. 

Without going into further detail on MacCannell's discussion of tourism, it seems to me that the paradoxical idea of "staged authenticity" provides a useful framework for understanding how artists are required to stage their working process for the social media Camera, as well as to construct and perform their own persona as an artist, since this is at least as important to their success as the quality of their work. Perhaps the archetype of the dilemma artists face today, as Bishop explains this, is the TV painter Bob Ross, whose legacy has been continued since his death via [YouTube](https://www.youtube.com/@bobross_thejoyofpainting). I would imagine that there are some interesting art-theory discussions of Bob Ross as a (posthumous) social media influencer that I don't know about, but he does seem to exemplify the paradoxical principle that as an artist, the more (algorithmically) visible you become to a mass audience, the less seriously your work itself it taken by highbrow art critics/theorists. It's a problem of credibility faced today not only by artists but by many other creative professionals trying to make a career on social media platforms, from math teachers to philosophy professors. While the requirements in each case remain the same---self-branding, optimized content, emotionally upbeat performance, etc.---female creators in particular are required to **perform** both their professional identity and their gender identity in accordance with social expectations.

Of course, while all of the artists interviewed by Bishop in her digital ethnography project were women, a huge number of social media creators are men, which raises a much larger question beyond the scope of Bishop's research project: in short, how do the dynamics of social media platforms affect male influencers, both in terms of the very different kinds of content they produce (technical subjects, music, sports, etc.) and the different kinds of stereotypical gender roles that they are required to perform in order to maximize their own visibility. I leave you to think about this. 

In order to contextualize the extent of influencer creep and avoid it defaulting to a purely theoretical discussion, I think it would be useful for us to share examples that connect to Bishop's discussion in some way. I'll conclude, then, with some examples of social media influencers that in my view exemplify the various components of influencer creep as Bishop describes it. The creators in question are women, but I also include both some male creators and one trans creator, in case any of you are interested in exploring influencer creep in relation to other gender identities. 

Although all of the creators in question operate across multiple platforms, I will limit myself to posting their YouTube channel page, since this typically also includes links to their other social media profiles and/or website. I'd recommend taking a look at all of them and selecting a couple from the list to look at more closely. Any of them would make for excellent case studies in the phenomenon of influencer creep. 

- [Karen Cheng](https://www.youtube.com/@karenxcheng) (low-budget social media content creation)
- [Math Queen](https://www.youtube.com/@MathQueenSusanne) (mathematics education by "Susanne from Germany")
- [Nicole van der Hoeven](https://www.youtube.com/@nicolevdh) (PKM (Personal Knowledge Management) expert, specializing in the note-taking app Obsidian)
- [Ellie Anderson](https://youtu.be/UUXXmHkI-Ug) (hosts the Overthink Podcast philosophy channel and podcast and philosophy channel) 

See also:

- [Proper Honest Tech](https://www.youtube.com/@ProperHonestTech) (MacOS/iOS-oriented tech channel; don't know the guy's name)
- [Theoretically Media](https://www.youtube.com/@TheoreticallyMedia) (generative AI; "My name is Tim")
- [Rick Beato](https://www.youtube.com/@RickBeato) (music industry, music theory, extended interviews with famous musicians)
- [ContraPoints](https://www.youtube.com/@ContraPoints) (cultural analysis by transgender cultural critic Natalie Wynn)

I also encourage you to share any examples of social media influencers that you find interesting or that you think exemplify the various components of influencer creep as Bishop describes it.

**Further reading**\
[Brooke Erin Duffy](https://www.brookeduffy.com/), **(Not) Getting Paid to Do What You Love: Gender and Aspirational Labor in the Social Media Economy** (New Haven: Yale University Press, 2017/2022).\
---, "[Influencer culture is everywhere---even in academia](https://www.salon.com/2022/04/30/influencer-culture-is-everywhere-even-in-academia/)" (**Salon**, 30 April 2022)\
---, [Public Scholarship](https://www.brookeduffy.com/new-page-3)\

[**Creators and Platform Labor Working Group**](https://www.creator-studies.com/) (Cornell University)

***



