---
title: "Platform Effects"
subtitle: "Engineering Popularity on Music Platforms"
toc: false
---

**Platforms**\
[Soundcloud](https://soundcloud.com/)\
[Bandcamp](https://bandcamp.com/)\
[Spotify](https://www.spotify.com/)\
[Peloton](https://www.onepeloton.com/)\
[Mixcloud](https://mixcloud.com/)\
[NTS Radio](https://www.ntsradio.com/)\
[Tidal](https://tidal.com/)\
[Youtube Music](https://music.youtube.com/)\

::: {.column-margin}

<small>David Hesmondhalgh, Ellis Jones, and Andreas Rauh, "[Soundcloud and Bandcamp as Alternative Music Platforms](https://journals.sagepub.com/doi/epub/10.1177/2056305119883429)"<br><br>Jeremy Wade Morris, "[Music Platforms and the Optimization of Culture](https://journals.sagepub.com/doi/epub/10.1177/2056305120940690)"<br><br>Robin James, "[Moving in Stereo](https://reallifemag.com/moving-in-stereo/)"<br><br>D. Bondy Valdovinos Kaye, "[JazzTok: Creativity, Community, and Improvisation on TikTok](https://scholarlypublishingcollective.org/uip/jac/article/6/2/92/383572/JazzTok-Creativity-Community-and-Improvisation-on)"</small>

:::

**Key Concepts**\
algorithmic recognizability -- affective engineering -- behavioural skeuomorphism -- contingency (of cultural commodities) -- culture of connectivity -- cultural optimization -- platformization -- platform effects -- producer/consumer-oriented platforms -- vibe

***

After beginning our consideration of contemporary social media's **platform cultures** by focusing on books and reading, this week we turn our attention to the role of social media platforms not just in the distribution and consumption of popular music, but also in shaping it as a form of cultural expression by the particular technological and economic infrastructures of the platforms themselves, leading to the forms of **cultural optimization** detailed by Jeremy Wade Morris in his article.

**Fake Musicians**

Among this week's readings, I was particularly intrigued by the section of Morris's article on what he calls "sonic optimization" by musicians on Spotify that discusses fake artists. By coincidence, I had just recently been watching some YouTube videos about the increasingly common phenomenon of "fake musicians" on social media, i.e. musical content creators that appropriate musical materials such as guitar solos, or even original compositions, from creators with very small numbers of followers, and pass them off as their own, even monetizing them by selling them as transcriptions or guitar tabs. Perhaps the most notorious recent case in point is Giacomo Turra. Here's Rick Beato's backgrounder:

{{< video https://www.youtube.com/embed/Y_S18U8guLM >}}

The source of the story is this video from a few months ago is Bradford bass-guitarist Danny Sapko's channel (don't be put off by his heavy Yorkshire accent!):

{{< video https://www.youtube.com/embed/CI4nuce3ppA >}}

Both videos are short and I encourage you to take a look at them. As Sapko describes it here, this is another kind of problem involving the relentless quest for what Jeremy Wade Morris calls **algorithmic visibility** (or elsewhere, recognizability). Turra's primary platform, it turns out, is Instagram, and Sapko's video comprehensively documents his appropriation of lesser-known musicians' guitar solos and compositions for his own monetary gain.

I wonder how you see this example in relation to the other examples of "fake artists" and cloned musics that Morris documents in his discussion of sonic/data/infrastructural optimization.

Referring to the strategies and hacks of Spotify's musical fakers, spammers, and cloners at the end of his article, Morris intriguingly suggests that rather than simply morally condemning them, they can be seen as effects of the platform itself and its particular technological and economic infrastructure:

> While it might seem---aesthetically, morally, or subjectively---that cloners, fakers, and spammers are simply exploiting or manipulating platforms, their actions may also be viewed as rational deci-
sions within and reactions to platform affordances and boundaries. Their actions may raise concerns about eventual impacts on musical cultures, users, other musicians, and even platform governance, but this optimized music also continues to provide platforms with more content and thus more potential for collecting data (Morris 2020: 8).

The second sentence also suggests an explanation for the apparent leniency of music platforms like Spotify (or in the case of Giacomo Turra, Instagram) towards such strategies, as long as it doesn't negatively impact their own commercial interests, or violate major-label property rights. After reading Morris's article, I was wondering what he might have to say about the Giacomo Turra scandal and whether he would see it in a similar light to his description of other "fake artists". If you have chance to watch the videos posted above, tell me what you think! Should music platforms be doing more to clamp down on fake artists?

**Vibes**

Robin James's article on Spotify's shift of music culture away from genre to what she calls **vibe** (in contrast to Peloton, as she explains), introduces a key concept that we'll be returning to in the last week of the course when we discuss internet aesthetics.

For now, I think her account of how Spotify has **reoriented** the popular understanding of music away from the traditional framework of genre to the more nebulous one of vibe (a phenomenon that she suggests is by no means limited to music culture but extends across the spectrum of neoliberal capitalist society) is thought-provoking, and I wonder what other examples---musical or otherwise--- it brings to mind for you.

What seems clear is that the vibe phenomenon that James is talking about in relation to music can also be observed on other social media platforms, most notably of course YouTube. The most obvious example of such a "vibe music" would be the proliferating playlists of LoFi Hip Hop, a style of low-key, ambient instrumental hip hop associated with Japanese DJs (though not limited to them) and visually inseparable from  anime. Typically framed under the rubric of music for specific contexts---music **for** studying, being sad to, etc.---LFHH seems like the archetypal example of vibe music, although the same could be said of other styles that are musically very different (the many shades of vaporwave, or post-rock). What seems to link these otherwise diverse styles is their **affective** dimension, or what the British cultural theorist Raymond Williams used to call a particular **structure of feeling**. 

As I say, we'll be returning to this topic in the final week, but I included Robin James's article this week as an introduction to thinking about the role of social media platforms as a force shaping (and arguably constraining) musical culture itself.

The LoFi Hip Hop style has been around for quite a while now and I'm assuming that at least some of you are already familiar with it. But since we're talking about vibes, it seems appropriate to play you out with the LoFi Girl channel livestream. Maybe you'll listen to it while writing your next paper? ;)

{{< video https://www.youtube.com/embed/CI4nuce3ppA >}}

I'm embedding below the Spotify playlists referenced in Jeremy Wade Morris's article, along with a short list of recommended further reading if you're interested in digging deeper into Spotify for your Platform Case Study paper. 

If you're interested in focusing on a music platform for that assignment, two other platforms to consider using David Hesmondhalgh et al.'s article on SoundCloud and Bandcamp as a model would be [Mixcloud](https://mixcloud.com) and [NTS Radio](https://www.ntsradio.com/)\, both used extensively by radio DJs. 

***

**Playlists**

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/0nosUZKpwQbGDvKJGuZzBX?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/37i9dQZF1DWWBHeXOYZf74?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

**Further Reading**\
Maria Eriksson, Rasmus Fleischer, Anna Johansson, Pelle Snickars, and Patrick Vonderau, **Spotify Teardown: Inside the Black Box of Streaming Music** (Cambridge, MA: MIT Press, 2019).

Liz Pelly, "[The Problem with Muzak](https://thebaffler.com/salvos/the-problem-with-muzak-pelly)" (**The Baffler** 37 (December 2017)).

---, **Mood Machine: The Rise Of Spotify And The Costs Of The Perfect Playlist** (London: Verso, 2025).

***